
package Vista;
import Controladores.GestorGestionServicios;
import java.awt.Color;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import Clases.RespaldoDatos;


/**
 *
 * @author Sergio Sánchez
 */
public class GestionServicios extends javax.swing.JFrame {
    
    

    /**
     * Creates new form GestionServicios
     */
    public GestionServicios(String titulo, RespaldoDatos almacenamiento) {
        initComponents();
        GestorGestionServicios gestionServicio = new GestorGestionServicios(this, almacenamiento);
        setVisible(true);
        setTitle(titulo);
        setLocationRelativeTo(null);
        setResizable(false);
    }
     public JButton getBtnAfiliados() {
        return btnAfiliados;
    }

    public JButton getBtnConsultorios() {
        return btnConsultorios;
    }

    public JButton getBtnMedicos() {
        return btnMedicos;
    }

    public JButton getBtnRegresar() {
        return btnRegresar;
    }

    public JButton getBtnServicios() {
        return btnServicios;
    }
    public void addBtnAfiliadosListener(MouseListener listenerBotones){
        btnAfiliados.addMouseListener(listenerBotones);
    }
    
    public void addBtnMedicosListener(MouseListener listenerBotones){
        btnMedicos.addMouseListener(listenerBotones);
    }
    
    public void addBtnConsultoriosListener(MouseListener listenerBotones){
        btnConsultorios.addMouseListener(listenerBotones);
    }
    
    public void addBtnServiciosListener(MouseListener listenerBotones){
        btnServicios.addMouseListener(listenerBotones);
    }
    
    public void addBtnRegresarListener(MouseListener listenerBotones){
        btnRegresar.addMouseListener(listenerBotones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnAfiliados = new javax.swing.JButton();
        btnMedicos = new javax.swing.JButton();
        btnConsultorios = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Gestion de servicios");

        btnAfiliados.setText("Afiliados");

        btnMedicos.setText("Médicos");
        btnMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicosActionPerformed(evt);
            }
        });

        btnConsultorios.setText("Consultorios");

        btnServicios.setText("Servicios médicos");

        btnRegresar.setText("Regresar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAfiliados, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(btnMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsultorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblTitulo)
                .addGap(53, 53, 53)
                .addComponent(btnAfiliados, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConsultorios, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMedicosActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfiliados;
    private javax.swing.JButton btnConsultorios;
    private javax.swing.JButton btnMedicos;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnServicios;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
